package main

// import "fmt"

// func logging() {
// 	fmt.Println("aplikasi selesai dijalankan")
// }

// func runApplication(value int) {
// 	defer logging() // ? dieksekusi terakhir ketika dijalankan dan diletakkan di posisi diatas
// 	fmt.Println("aplikasi dijalankan")
// 	result := 10 / value // ! dan ketika pada block code ini terjadi error, maka func logging akan tetap dijalankan
// 	fmt.Println("Result", result)
// }

// func main() {
// 	runApplication(10)
// }
